# -*- coding: utf-8 -*-
f = open(r'C:\Users\fortu\Desktop\Project\Demo\desktop\src\main\database\connection.ts', 'w', encoding='utf-8')
f.write('// @ts-nocheck\n')
f.write("import initSqlJs, { Database } from 'sql.js';\n")
f.write("import * as fs from 'fs';\n")
f.write("import * as path from 'path';\n")
f.write("import { app } from 'electron';\n")
f.write("import * as bcrypt from 'bcryptjs';\n")
f.write('\n')
f.write('let db: Database | null = null;\n')
f.write('let dbPath: string;\n')
f.write('\n')
f.write('export function getDb(): Database {\n')
f.write("  if (!db) throw new Error('Database not initialized.');\n")
f.write('  return db;\n')
f.write('}\n')
f.write('\n')
f.write('export async function initDatabase(): Promise<void> {\n')
f.write('  try {\n')
f.write('    const SQL = await initSqlJs({\n')
f.write('      locateFile: (file) => {\n')
f.write("        if (app.isPackaged) return path.join(process.resourcesPath, 'sql-wasm.wasm');\n")
f.write("        return path.join(__dirname, '../../../node_modules/sql.js/dist', file);\n")
f.write('      },\n')
f.write('    });\n')
f.write("    const userDataPath = app.getPath('userData');\n")
f.write("    dbPath = path.join(userDataPath, 'contract_risk.db');\n")
f.write('    const dbDir = path.dirname(dbPath);\n')
f.write('    if (!fs.existsSync(dbDir)) fs.mkdirSync(dbDir, { recursive: true });\n')
f.write('    if (fs.existsSync(dbPath)) {\n')
f.write('      const buffer = fs.readFileSync(dbPath);\n')
f.write('      db = new SQL.Database(buffer);\n')
f.write('      console.log(`Database loaded from: ${dbPath}`);\n')
f.write('    } else {\n')
f.write('      db = new SQL.Database();\n')
f.write("      console.log('New database created in memory');\n")
f.write('    }\n')
f.write("    db.run('PRAGMA foreign_keys = ON');\n")
f.write('    db.run(\'PRAGMA encoding = "UTF-8"\');\n')
f.write('    createTables();\n')
f.write('    migrateDatabase();\n')
f.write('    initializeDefaultData();\n')
f.write('    saveDatabase();\n')
f.write("    console.log('Database initialized successfully');\n")
f.write('  } catch (error) {\n')
f.write("    console.error('Failed to initialize database:', error);\n")
f.write('    throw error;\n')
f.write('  }\n')
f.write('}\n')
f.write('\n')
f.write('function createTables(): void {\n')
f.write("  if (!db) throw new Error('Database not initialized');\n")
f.write('  db.run(`CREATE TABLE IF NOT EXISTS users (\n')
f.write('    id INTEGER PRIMARY KEY AUTOINCREMENT,\n')
f.write('    username TEXT UNIQUE NOT NULL,\n')
f.write('    password_hash TEXT NOT NULL,\n')
f.write('    display_name TEXT NOT NULL,\n')
f.write("    role TEXT DEFAULT \'user\' CHECK(role IN (\'user\', \'admin\')),\n")
f.write('    login_attempts INTEGER DEFAULT 0,\n')
f.write('    locked_until DATETIME,\n')
f.write('    last_login DATETIME,\n')
f.write('    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n')
f.write('    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n')
f.write('  )`);\n')
f.write('  db.run(`CREATE TABLE IF NOT EXISTS projects (\n')
f.write('    id INTEGER PRIMARY KEY AUTOINCREMENT,\n')
f.write('    name TEXT NOT NULL,\n')
f.write('    description TEXT,\n')
f.write('    password_hash TEXT,\n')
f.write('    failed_attempts INTEGER DEFAULT 0,\n')
f.write('    locked_until DATETIME,\n')
f.write('    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,\n')
f.write('    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n')
f.write('    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n')
f.write('    deleted_at DATETIME\n')
f.write('  )`);\n')
f.write('  db.run(`CREATE TABLE IF NOT EXISTS documents (\n')
f.write('    id INTEGER PRIMARY KEY AUTOINCREMENT,\n')
f.write('    project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,\n')
f.write('    name TEXT NOT NULL,\n')
f.write('    original_filename TEXT NOT NULL,\n')
f.write('    file_path TEXT NOT NULL,\n')
f.write('    file_type TEXT NOT NULL,\n')
f.write('    file_size INTEGER NOT NULL DEFAULT 0,\n')
f.write("    status TEXT DEFAULT \'pending\' CHECK(status IN (\'pending\', \'processing\', \'completed\', \'failed\')),\n")
f.write('    error_message TEXT,\n')
f.write('    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n')
f.write('    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n')
f.write('    deleted_at DATETIME\n')
f.write('  )`);\n')
f.write('  db.run(`CREATE TABLE IF NOT EXISTS clauses (\n')
f.write('    id INTEGER PRIMARY KEY AUTOINCREMENT,\n')
f.write('    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,\n')
f.write('    clause_number TEXT NOT NULL,\n')
f.write('    title TEXT,\n')
f.write('    content TEXT NOT NULL,\n')
f.write('    level INTEGER DEFAULT 1,\n')
f.write('    parent_id INTEGER REFERENCES clauses(id),\n')
f.write('    order_index INTEGER DEFAULT 0,\n')
f.write('    page_number INTEGER,\n')
f.write('    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n')
f.write('    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n')
f.write('  )`);\n')
f.write('  db.run(`CREATE TABLE IF NOT EXISTS risk_rules (\n')
f.write('    id INTEGER PRIMARY KEY AUTOINCREMENT,\n')
f.write('    name TEXT NOT NULL,\n')
f.write("    category TEXT NOT NULL DEFAULT '\u5176\u4ed6',\n")
f.write('    description TEXT,\n')
f.write("    risk_level TEXT NOT NULL CHECK(risk_level IN ('high', 'medium', 'low')),\n")
f.write("    keywords TEXT NOT NULL DEFAULT '[]',\n")
f.write('    pattern TEXT,\n')
f.write('    is_enabled INTEGER NOT NULL DEFAULT 1,\n')
f.write('    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n')
f.write('    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n')
f.write('  )`);\n')
f.write('  db.run(`CREATE TABLE IF NOT EXISTS risk_matches (\n')
f.write('    id INTEGER PRIMARY KEY AUTOINCREMENT,\n')
f.write('    clause_id INTEGER NOT NULL REFERENCES clauses(id) ON DELETE CASCADE,\n')
f.write('    rule_id INTEGER NOT NULL REFERENCES risk_rules(id),\n')
f.write("    risk_level TEXT NOT NULL CHECK(risk_level IN ('high', 'medium', 'low')),\n")
f.write('    matched_text TEXT NOT NULL,\n')
f.write('    suggestion TEXT,\n')
f.write("    user_adjusted_level TEXT CHECK(user_adjusted_level IN ('high', 'medium', 'low')),\n")
f.write('    created_at DATETIME DEFAULT CURRENT_TIMESTAMP\n')
f.write('  )`);\n')
f.write('  db.run(`CREATE TABLE IF NOT EXISTS annotations (\n')
f.write('    id INTEGER PRIMARY KEY AUTOINCREMENT,\n')
f.write('    clause_id INTEGER NOT NULL REFERENCES clauses(id) ON DELETE CASCADE,\n')
f.write('    user_id INTEGER NOT NULL REFERENCES users(id),\n')
f.write("    type TEXT NOT NULL CHECK(type IN ('comment', 'suggestion', 'question', 'issue')),\n")
f.write('    content TEXT NOT NULL,\n')
f.write("    status TEXT DEFAULT 'active' CHECK(status IN ('active', 'resolved', 'deleted')),\n")
f.write('    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n')
f.write('    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP\n')
f.write('  )`);\n')
f.write('  db.run(`CREATE TABLE IF NOT EXISTS document_versions (\n')
f.write('    id INTEGER PRIMARY KEY AUTOINCREMENT,\n')
f.write('    document_id INTEGER NOT NULL REFERENCES documents(id) ON DELETE CASCADE,\n')
f.write('    version_number INTEGER NOT NULL,\n')
f.write('    content TEXT NOT NULL,\n')
f.write('    created_by INTEGER NOT NULL REFERENCES users(id),\n')
f.write('    comment TEXT,\n')
f.write('    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,\n')
f.write('    UNIQUE(document_id, version_number)\n')
f.write('  )`);\n')
f.write('  db.run(`CREATE TABLE IF NOT EXISTS audit_logs (\n')
f.write('    id INTEGER PRIMARY KEY AUTOINCREMENT,\n')
f.write('    user_id INTEGER NOT NULL REFERENCES users(id),\n')
f.write('    action TEXT NOT NULL,\n')
f.write('    resource_type TEXT NOT NULL,\n')
f.write('    resource_id INTEGER,\n')
f.write('    details TEXT,\n')
f.write('    ip_address TEXT,\n')
f.write('    created_at DATETIME DEFAULT CURRENT_TIMESTAMP\n')
f.write('  )`);\n')
f.write("  db.run('CREATE INDEX IF NOT EXISTS idx_users_username ON users(username)');\n")
f.write("  db.run('CREATE INDEX IF NOT EXISTS idx_projects_user_id ON projects(user_id)');\n")
f.write("  db.run('CREATE INDEX IF NOT EXISTS idx_documents_project ON documents(project_id)');\n")
f.write("  db.run('CREATE INDEX IF NOT EXISTS idx_clauses_document ON clauses(document_id)');\n")
f.write("  db.run('CREATE INDEX IF NOT EXISTS idx_risk_matches_clause ON risk_matches(clause_id)');\n")
f.write("  db.run('CREATE INDEX IF NOT EXISTS idx_annotations_clause ON annotations(clause_id)');\n")
f.write("  db.run('CREATE INDEX IF NOT EXISTS idx_document_versions_document ON document_versions(document_id)');\n")
f.write('}\n')
f.write('\n')
f.write('function initializeDefaultData(): void {\n')
f.write("  if (!db) throw new Error('Database not initialized');\n")
f.write('\n')
f.write("  const adminCheck = db.exec('SELECT id FROM users WHERE username = ?', ['admin']);\n")
f.write('  if (!(adminCheck.length > 0 && adminCheck[0].values.length > 0)) {\n')
f.write("    const h = bcrypt.hashSync('Admin@123', 10);\n")
f.write('    db.run(`INSERT INTO users (username,password_hash,display_name,role) VALUES (?,?,?,?)`,\n')
f.write("      ['admin', h, '" + '\u7cfb\u7d71\u7ba1\u7406\u54e1' + "', 'admin']);\n")
f.write("    console.log('Default admin user created (username: admin, password: Admin@123)');\n")
f.write('  }\n')
f.write('\n')
f.write("  const u1Check = db.exec('SELECT id FROM users WHERE username = ?', ['user1']);\n")
f.write('  if (!(u1Check.length > 0 && u1Check[0].values.length > 0)) {\n')
f.write("    const h = bcrypt.hashSync('User@123', 10);\n")
f.write('    db.run(`INSERT INTO users (username,password_hash,display_name,role) VALUES (?,?,?,?)`,\n')
f.write("      ['user1', h, '" + '\u666e\u901a\u7528\u6236' + "', 'user']);\n")
f.write("    console.log('Default user1 created (username: user1, password: User@123)');\n")
f.write('  }\n')
f.write('\n')
f.write("  const testCheck = db.exec('SELECT id FROM users WHERE username = ?', ['test']);\n")
f.write('  if (!(testCheck.length > 0 && testCheck[0].values.length > 0)) {\n')
f.write("    const h = bcrypt.hashSync('Test@123', 10);\n")
f.write('    db.run(`INSERT INTO users (username,password_hash,display_name,role) VALUES (?,?,?,?)`,\n')
f.write("      ['test', h, '" + '\u6e2c\u8a66\u7528\u6236' + "', 'user']);\n")
f.write("    console.log('Default test user created (username: test, password: Test@123)');\n")
f.write('  }\n')
f.write('\n')
f.write("  const rCnt = db.exec('SELECT COUNT(*) as count FROM risk_rules');\n")
f.write('  const cnt = rCnt.length > 0 && rCnt[0].values.length > 0 ? rCnt[0].values[0][0] : 0;\n')
f.write('  if (cnt === 0) {\n')
f.write('    const rules = [\n')

rules = [
    ('\u4ed8\u6b3e\u671f\u9650\u904e\u9577', '\u4ed8\u6b3e\u689d\u4ef6', 'high',
     '["\u4ed8\u6b3e","\u652f\u4ed8","\u7d50\u7b97"]',
     '\u5efa\u8b70\u5c07\u4ed8\u6b3e\u671f\u9650\u7e2e\u77ed\u81f330\u65e5\u5167'),
    ('\u9055\u7d04\u91d1\u6bd4\u4f8b\u904e\u9ad8', '\u9055\u7d04\u8cac\u4efb', 'high',
     '["\u9055\u7d04\u91d1","\u8ce0\u511f\u91d1","\u7f70\u6b3e"]',
     '\u5efa\u8b70\u5c07\u9055\u7d04\u91d1\u6bd4\u4f8b\u8abf\u6574\u70ba10%-20%'),
    ('\u7ba1\u8f44\u5730\u4e0d\u5229', '\u7ba1\u8f44\u5730', 'medium',
     '["\u7ba1\u8f44","\u4ed2\u88c1","\u8a34\u8a1f"]',
     '\u5efa\u8b70\u5c07\u7ba1\u8f44\u5730\u8a2d\u7f6e\u70ba\u6211\u65b9\u6240\u5728\u5730\u6cd5\u9662'),
    ('\u4fdd\u5bc6\u671f\u9650\u904e\u9577', '\u4fdd\u5bc6\u671f\u9650', 'medium',
     '["\u4fdd\u5bc6","\u5546\u696d\u79d8\u5bc6"]',
     '\u5efa\u8b70\u5c07\u4fdd\u5bc6\u671f\u9650\u8abf\u6574\u70ba3\u5e74'),
    ('\u81ea\u52d5\u7e8c\u7d04\u689d\u6b3e', '\u81ea\u52d5\u7e8c\u7d04', 'high',
     '["\u81ea\u52d5\u7e8c\u7d04","\u81ea\u52d5\u5ef6\u671f"]',
     