# -*- coding: utf-8 -*-
import sys
out = open(r'C:\Users\fortu\Desktop\Project\Demo\desktop\src\main\database\connection.ts', 'w', encoding='utf-8')

# Header
out.write('// @ts-nocheck\n')
out.write("import initSqlJs, { Database } from 'sql.js';\n")
out.write("import * as fs from 'fs';\n")
out.write("import * as path from 'path';\n")
out.write("import { app } from 'electron';\n")
out.write("import * as bcrypt from 'bcryptjs';\n\n")
out.write('let db: Database | null = null;\n')
out.write('let dbPath: string;\n\n')
out.write('export function getDb(): Database {\n')
out.write("  if (!db) throw new Error('Database not initialized.');\n")
out.write('  return db;\n}\n\n')

# initDatabase
out.write('export async function initDatabase(): Promise<void> {\n')
out.write('  try {\n')
out.write('    const SQL = await initSqlJs({\n')
out.write('      locateFile: (file) => {\n')
out.write("        if (app.isPackaged) return path.join(process.resourcesPath, 'sql-wasm.wasm');\n")
out.write("        return path.join(__dirname, '../../../node_modules/sql.js/dist', file);\n")
out.write('      },\n    });\n')
out.write("    const userDataPath = app.getPath('userData');\n")
out.write("    dbPath = path.join(userDataPath, 'contract_risk.db');\n")
out.write('    const dbDir = path.dirname(dbPath);\n')
out.write('    if (!fs.existsSync(dbDir)) fs.mkdirSync(dbDir, { recursive: true });\n')
out.write('    if (fs.existsSync(dbPath)) {\n')
out.write('      const buffer = fs.readFileSync(dbPath);\n')
out.write('      db = new SQL.Database(buffer);\n')
out.write('      console.log(`Database loaded from: ${dbPath}`);\n')
out.write('    } else {\n')
out.write('      db = new SQL.Database();\n')
out.write("      console.log('New database created in memory');\n")
out.write('    }\n')
out.write("    db.run('PRAGMA foreign_keys = ON');\n")
out.write('    db.run(\'PRAGMA encoding = "UTF-8"\');\n')
out.write('    createTables();\n')
out.write('    migrateDatabase();\n')
out.write('    initializeDefaultData();\n')
out.write('    saveDatabase();\n')
out.write("    console.log('Database initialized successfully');\n")
out.write('  } catch (error) {\n')
out.write("    console.error('Failed to initialize database:', error);\n")
out.write('    throw error;\n  }\n}\n\n')

out.close()
print('header done')
